### PR TITLE
Add drop and dropM

### PR DESCRIPTION
**Pull request by chris-martin**
This adds `drop` and `dropM` proposed by #138. I also added a test suite to verify the two properties that I assert in the docs:

```haskell
L.fold (L.drop n folder) list = L.fold folder (Data.List.genericDrop n list)

L.foldM (L.dropM n folder) list = L.foldM folder (Data.List.genericDrop n list)
```

### CODE REVIEW

**Comment by Gabriel439** [comment]
@chris-martin: The main suggestion I have is to use `doctest` as the test suite and turn the example in the docs into a doctest.  That way the test suite requires less maintenance

**Comment by nikita-volkov** [comment]
Seems like something should be done about the "pre"-prefix convention. Either functions like this should all be prefixed or we should do something about "premap" and "prefilter".

**Comment by chris-martin** [comment]
Updated.

I'm not sure how to run the doctests. Is there a way to add doctest to the nix shell environment? The current shell expression is `(pkgs.haskell.lib.doBenchmark pkgs.haskellPackages.foldl).env` and I don't know how to modify that to add additional packages.

**Comment by Gabriel439** [comment]
@chris-martin: I think something like this would work:

```
(pkgs.haskell.lib.doBenchmark
  (pkgs.haskell.lib.addBuildTool
    pkgs.haskellPackages.foldl
    pkgs.haskellPackages.doctest
  )
).env
```

... however usually I will have the test suite run the doctests using `Test.DocTest.doctest`:

https://hackage.haskell.org/package/doctest-0.16.2/docs/Test-DocTest.html#v:doctest

**Pull request merged**
