### PR TITLE
Added `mkFold1`

### PR DESCRIPTION
**Pull request by cjay**
The name seems odd, but I couldn't find a better one.

### CODE REVIEW

**Comment by Gabriel439** [comment]
It looks good.  Maybe you could name it `nonEmpty` (since it only succeeds if the sequence has at least one element)

**Comment by cjay** [comment]
I think the name should express that it takes the initial accumulator from the first element, so `accumFromHead` might be better. However since `foldl1'` is a familiar concept that is easily recognized by users, it would be very good to have it in the name. Unfortunately, calling it `fold1` sounds too close to `fold` which does something very different.

**Comment by Gabriel439** [comment]
What about naming it `_Fold1` so it looks like it is a pseudo-constructor (i.e. a variation on the `Fold` constructor that requires no initial accumulator)?

**Comment by cjay** [comment]
That sounds good, I renamed it.

**Comment by Gabriel439** [comment]
Awesome.  Thank you! :)

I will upload this in about a week.  There are just a few other additions I want to make before the next release.

**Comment by PierreR** [comment]
I thought `_` meant it was a prism ;-)

**Comment by michaelt** [comment]
It is a little confusing that the names are coming out so little uniform among themselves and with what you might expect from other libraries.  

Whatever they are called I was thinking it might be clearer if `mkFold1` had a `mkFold` named uniformly with it: `mkFold op seed = Fold op seed id` or something.  I was going to suggest `reduce` and `reduce1` but they're pretty lame. It seems anyway that there should be uniformity with `foldMap`.  `foldMap` by the way has a rather odd signature here.  It seems one wants a series:

     Fold :: (x -> a -> x) -> x -> (x -> b) -> Fold a b
     xxx :: (b -> a -> b) -> b -> Fold a b
     yyy :: (a -> a -> a) -> Fold a (Maybe)
     zzz :: Monoid m => (a -> m) -> Fold a m

Of course, of these only `yyy` (`mkFold1`) is not trivially definable by using `id` and so on directly with `Fold`. `zzz` is intuitively what `foldMap` should be, but I guess you are thinking its natural use is `foldMap Sum getSum` and `foldMap Product getProduct` etc. which makes sense.  (Of course, aping the `Foldable` nomenclature, which will now be pretty pervasive, would suggest: `fold :: Monoid m => Fold m m` ...)

The competition for names between `Fold` constructing functions and the `Fold` applying functions like `fold` and `scan` seems kind of inevitable though. It's too late but maybe `fold` should have just been called something like `apply` or maybe `foldable`.  I was thinking before that the applying functions should just be named after the type  of collection, `list` `foldable` `vector` etc., but that's probably not practical either.

**Pull request merged**
