### PR TITLE
Add instance Semigroupoid Fold

### LINKED ISSUE #110: instance Semigroupoid Fold
~~~~.hs
instance Semigroupoid Fold where
  o (Fold s1 b1 x1) (Fold s2 b2 x2) = Fold
    (\c a ->
      let c2' = s2 (snd c) a
          c1' = s1 (fst c) (x2 c2')
      in  (c1', c2')
    )
    (b1, b2)
    (x1 . fst)
~~~~

Seems to be a lawful instance although I have not done the proof. Also I cannot spot this functionality (`Fold b c -> Fold a b -> Fold a c`) in the existing exports.

### PR DESCRIPTION
**Pull request by lspitzner**
Fixes #110

### CODE REVIEW

**Comment by lspitzner** [comment]
Oh, looking at folds now i notice two things: We might want a strict pair as the state, and I forgot an INLINE o. What do you think regarding strict/non-strict pair?

**Comment by Gabriel439** [comment]
@lspitzner: Yeah, this should use a strict pair.  It's probably not necessary in newer versions of GHC where the strictness analyzer has gotten much better, but I still use the strict pair as a precaution

**Comment by Profpatsch** [comment]
What does this instance do, semantically?

```
> Control.Foldl.fold (Control.Foldl.mconcat &>> Control.Foldl.mconcat) [[1],[10],[100],[1000]]
[1,1,10,1,10,100,1,10,100,1000]
```

This is quite a senseless result, I cannot think of a situation where this is useful? Is this the only lawful instance and if yes, what operation does it represent?

**Comment by Gabriella439** [comment]
I don't know what the `&>>` operator in your example is from or what it is doing

**Pull request merged**
