### PR TITLE
Add "prefolding"

### PR DESCRIPTION
**Pull request by nikita-volkov**

### CODE REVIEW

**Comment by Gabriel439** [comment]
This is a special case of the handles function.  See: https://github.com/Gabriel439/Haskell-Foldl-Library/pull/58

**Comment by michaelt** [comment]
Lens `folded` uses `Foldable.foldr` if you are thinking of the example from #58, thus we see

     >>>  L.fold (prefolding  L.list ) ["abc","def"]
    "abcdef"

but 

    >>>  L.fold (L.handles folded  L.list ) ["abc","def"]
    "cbafed"

**Comment by nikita-volkov** [comment]
I'm also doubtful, whether the lens-based solution will perform on par due to layers of intermediate abstractions, that is besides them resolving to `foldr` as mentioned by @michaelt, which itself raises a fair suspicion about it needlessly aggregating the stack due to being used to reproduce the left fold in the end.

Also a resolution not to include this function is inconsistent with the `premap` function, which could as well be reproduced with something like `handles mapped`, that is besides it actually just being `lmap` of `Profunctor`.

**Comment by michaelt** [comment]
Right, so e.g. 

     main =  print $ L.fold  (prefolding L.maximum)
         [enumFromTo 1 (10^7), enumFromTo 1 (10^7::Int)]

takes ` real	0m0.261s`, while 
    main =  print $ L.fold  (L.handles folded  L.maximum) 
        [enumFromTo 1 (10^7), enumFromTo 1 (10^7::Int)]

takes  `real	0m2.024s`

It also uses as much space as it pleases.  But presumably one could arrange for this kind of traversal to use a left fold.

**Comment by Gabriel439** [comment]
Actually, this makes me suspect that `handles` itself is wrong if it's aggregating results in the wrong order.    I noticed that if I replace the `Endo m` in `Handler` with `Dual (Endo m)` then the results are in the correct order.  Let me fix that.

**Comment by michaelt** [comment]
Amazing. The little test I was using seems to be running slightly faster with the corrected `handles` than with `prefolding`.

**Comment by nikita-volkov** [comment]
Either way, I believe that it would be nice to have self-sufficient solutions in the "foldl" library. I, for instance, work on library projects, for which I am very skeptical about introducing dependencies to any lens-library. I'm hardly alone in this POV.

> Amazing! And the little test I was using seems to be running slightly faster with the corrected handles than with prefolding.

I honestly wonder how that can be possible.

**Comment by Gabriel439** [comment]
I think the reason why `handles` is running faster is because @nikita-volkov is using `foldl` instead of `foldl'`.  I think if he corrects it then both should run about roughly the same speed.

**Comment by Gabriel439** [comment]
However, what I can do is add a `folded` optic directly to `foldl` so that you can do what @nikita-volkov wants without importing `lens-family-core`/`lens` or without defining the optic manually.

**Comment by michaelt** [comment]
Changing to `foldl'` had already occurred to me. The one test I made was probably not ideal, I wrote it to exhibit accumulation to myself, which was the first thing that worried me about 'Lens.folded' . Here's the test fwiw https://gist.github.com/michaelt/abfcf781f83801481485

**Comment by Gabriel439** [comment]
Alright, so I fixed the backwards folding and also added a `folded` optic directly to the library so that you can get this behavior without depending on a lens library.

**Comment by nikita-volkov** [comment]
Thanks guys!

**Comment by Gabriel439** [comment]
You're welcome!

**Pull request closed without merging**
