### PR TITLE
instantiated `Profunctor` for `Fold`

### LINKED ISSUE #36: Fold looks a Profunctor
`Fold` looks like a profunctor:

    instance Profunctor Fold where
        lmap = premap
        rmap = fmap

Is there interest in declaring it as such?

### PR DESCRIPTION
**Pull request by srijs**
fixes #36

### CODE REVIEW

**Comment by srijs** [comment]
Sure, updated.

**Comment by Gabriel439** [comment]
Awesome!  Thank you for writing that up!

**Comment by Gabriel439** [comment]
I will upload this to Hackage soon.  Remind me if I forget

**Comment by Gabriel439** [comment]
Alright, this is up on Hackage as `foldl-1.0.11`

**Pull request merged**
