### PR TITLE
Add "either"

### PR DESCRIPTION
**Pull request by nikita-volkov**

### CODE REVIEW

**Comment by nikita-volkov** [comment]
Possibly this could be renamed to something like "interleave"

**Comment by Gabriel439** [comment]
@nikita-volkov: I think `either`/`eitherM` are good names, so don't worry

The main thing I was going to suggest is that you implement them like this:

```haskell
-- Inline the definition of the `_Left` and `_Right` prisms
_Left :: (Choice p, Applicative f) => p a (f b) -> p (Either a c) (f (Either b c))
_Left = ...

_Right :: (Choice p, Applicative f) => p a (f b) -> p (Either c a) (f (Either c b))
_Right = ...

either :: Fold a1 b1 -> Fold a2 b2 -> Fold (Either a1 a2) (b1, b2)
either l r = (,) <$> handles _Left l <*> handles _Right r

eitherM :: Applicative m => FoldM m a1 b1 -> FoldM m a2 b2 -> FoldM m (Either a1 a2) (b1, b2)
eitherM l r = (,) <$> handlesM _Left l <*> handlesM _Right r
```

The main reason I suggest doing this is that I imagine that people will be interested in generalizing this trick to sum types other than `Either`, and if they are implemented like that it will be easier for people to infer the general solution from the source

**Comment by nikita-volkov** [comment]
Check out the updates. On the afterthought, probably it would've been enough to specify that in docs instead.

**Comment by Gabriel439** [comment]
Thank you! 🙂

**Pull request merged**
