### PR TITLE
Add a few missing INLINABLE pragmas

### PR DESCRIPTION
**Pull request by sjakobi**
I assume that these pragmas were left out by accident, not intentionally.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Yeah, those omissions were unintentional.  Could you make one small change to make the annotation `INLINE` for the `Monoid` methods?  I find that `INLINE` gives the best performance for type class methods

**Comment by sjakobi** [comment]
> Could you make one small change to make the annotation INLINE for the Monoid methods?

Would you like me to make that change on all the instances in the package? There are quite a bunch of instances with INLINABLE pragmas.

**Comment by Gabriel439** [comment]
Yes.  Those were added back before I learned that `INLINE` was better

**Comment by sjakobi** [comment]
Done!

**Comment by Gabriel439** [comment]
Thanks! :)

**Pull request merged**
