### PR TITLE
Added mapM_

### PR DESCRIPTION
**Pull request by mitchellwrosen**
#49

### CODE REVIEW

**Comment by Gabriel439** [comment]
Oh, the problem seems to be the use of `void`, which entails a `Functor` constraint.  Maybe just line the equivalent behavior:

```haskell
mapM_ action = sink (\a -> action a >> return ())
```

**Comment by mitchellwrosen** [comment]
Oh, sorry, I only built against `lts-3.10`.

**Comment by Gabriel439** [comment]
Shouldn't it read "more general than `sink`"?

**Comment by mitchellwrosen** [comment]
I suppose it's more general in the effectful function, but less general in that it specializes the monoid to `()`. Shrug. I'll let you decide the correct wording for the comment :)

**Comment by Gabriel439** [comment]
Oh yeah, I forgot that `sink` is generalized to `Monoid`.  Actually, maybe make the type take a `(a -> m ()` instead and note that it is a specialized version of `sink`

**Comment by mitchellwrosen** [comment]
Done

**Pull request merged**
