### PR TITLE
Folds are trivially profunctors

### PR DESCRIPTION
**Pull request by jwiegley**

### CODE REVIEW

**Comment by treeowl** [comment]
It looks like this issue will shortly be able to be closed once my latest pull request goes through. I didn't notice it when I submitted a duplicate, and it looks like you decided to go with `profunctors` despite the dependency anyway.

**Comment by treeowl** [comment]
It looks like this is pretty much what I just submitted, except mine was written months later and lacks merge conflicts.

**Comment by Gabriel439** [comment]
Yeah, I eventually decided to relent and add the `Profunctors` instances.  The thing that changed my mind was that most people are moving off the Haskell Platform anyway, so I'm dropping my rule about only depending on things in the Haskell Platform.

I'd still like to see the `Profunctor` type class merged into `base`, though, as it is still a pretty heavy dependency at the moment, but nobody has complained yet.

**Comment by treeowl** [comment]
@Gabriel439, I think Ed might be upset about the orphan potential of moving it to `base`. I'm also a bit disturbed by the fact that `rmap = fmap` seems to be pretty much always legal, and there's a disturbingly close relationship between `lmap` and `contramap`. To my mind, that makes the `Profunctor` class a bit ... awkward.

**Comment by Gabriel439** [comment]
So this ended up being reimplemented elsewhere (#42 was the finishing change).  Sorry that I didn't merge this a long time ago.  The main thing that changed was that the Haskell Platform is being deemphasized by the Haskell community so I'm less picky about dependencies outside of the Haskell Platform.  In the process, I forgot about your original pull request.  I'm sorry about that.

**Comment by Gabriel439** [comment]
@treeowl Yeah, I'm actually really surprised that there isn't a `Functor` constraint on `Profunctor`.  However, there's no way to make it work with `Contravariant` because the contravariant type parameter of the type constructor implementing `Profunctor` would be in the wrong place.

The latter is sort of an unavoidable problem of Haskell's way of doing type classes (and part of the reason why the `Profunctor` and `Bifunctor` classes even exists)

**Comment by treeowl** [comment]
@Gabriel439, I think there's a (different) problem with `Functor`. You'd need a context looking like

```haskell
class (forall a . Functor p a) => Profunctor p where ...
```

I don't personally know of a way to express that, and I'm not at all sure it's possible.

**Comment by Gabriel439** [comment]
Oh yeah, the only way you could express that in Haskell is something hacky like this:

```haskell
class Functor' p where
    fmap' :: (a -> b) -> p i a -> p i b

instance Functor' p => Profunctor p
```

This is basically the same trick that the `Alternative` class uses so that people can have higher-kinded `Monoid` constraints.

**Comment by jwiegley** [comment]
@Gabriel439 No worries, just glad to see the instance get in one way or another.

**Pull request closed without merging**
